### ISSUE TITLE
datasets problem

### ISSUE THREAD

**Issue by avenger123456** [wanghao9610/TMANet#1]
How to download or generate leftImg8bit_sequence? I put the leftImg8bit instead to do eval.sh , but it didn't work. Looking forward to your reply.

**Comment by wanghao9610** [comment]
Hi, please browse the Cityscapes dataset download webpage(https://www.cityscapes-dataset.com/downloads/), it may require a login and you may need to register a count. After login, in the middle part of the webpage, you will see a message 'The following packages are available upon request. If you require any of them for your research, please send an email(link) including your Cityscapes username and a list of required packages.', click the email link and send an email to require the 'leftImg8bit_sequence_trainvaltest.zip' package including your Cityscapes username. You will get a link to download them. By the way, the size of .zip file is 325Gb, you need enough disk space, spare network, and time to download.
