### ISSUE TITLE
do we need to convert the cityscape dataset with 35 classes to 19 classes?

### ISSUE THREAD

**Issue by QuLiao1117** [wanghao9610/TMANet#13]
Since the downloaded cityscape dataset has 35 classes, I can't train the previous code due to the setting of num_classes=19.
So I modify the code to num_classes=35, and it begins to train. But I'm worrying about should I use some script to turn the 35 classes into 19 classes? Hope to listen to your advice, thanks.

**Comment by wanghao9610** [comment]
Hi:
    In our experiments, we have converted the original 35 num_classes labels to 19 num_classes labels. You can get some help from the issue #11 .

**Comment by QuLiao1117** [comment]
Thanks! I successfully convert the dataset into 19 classes with that script.
