### ISSUE TITLE
我是新人，请问您的论文真的是 SOTA 吗？（如果冒犯，请多谅解）

### ISSUE THREAD

**Issue by zhangxiann** [wanghao9610/TMANet#14]
您好。我阅读了您的论文，是一篇非常棒的工作。
但是 TMANet 是 CitySpace Val 数据集 semantic segmentation 的 SOTA 吗？
我看到 paperswithcode 上，有很多方法的 mIoU 都超过了您论文中的数据。
![image](https://user-images.githubusercontent.com/12131262/132991885-e7f45c58-a7a8-4d25-bd34-206e9c46de66.png)

[https://paperswithcode.com/sota/semantic-segmentation-on-cityscapes](https://paperswithcode.com/sota/semantic-segmentation-on-cityscapes)
请问您是出于什么原因没有和它们进行对比呢？或者它们是同一个任务吗？

**Comment by wanghao9610** [comment]
The above leaderboard is rank of image semantic segmentation, and TMANet is a method for video semantic segmentation, which is not the same with semantic segmentation. Cityscapes dataset has two different part and two different leaderborads, one for image semantic segmentaiton(w/o sequence image), one for video semantic segmentation(w sequence image). You should refer to the Video Semantic Segmentation leaderboard. 
When we pulished the paper, our work is SOTA with ResNet-50 backbone(80.3% mIoU on Cityscapes), with stronger bachbone, TMANet can achieve better performance. And now may have new method achieving new SOTA, you can search on arxiv with yourself. Hope it is helpful!

**Comment by zhangxiann** [comment]
I'm sorry, but why it is not the same task? The data and labels are all the same? What's the difference between the two tasks?
