### ISSUE TITLE
inferencing with my own video

### ISSUE THREAD

**Issue by fjremnav** [wanghao9610/TMANet#19]
I have a video which I want to test with cityscapes pretrained model. 
Is there a script to do this?
Evaluation script seems to handle cityscapes validation dataset only

FC

**Comment by fjremnav** [comment]
How many past images are used to predict current image in inferencing?

Thanks,

**Comment by wanghao9610** [comment]
The sequence_num is 4 for Camvid and 2 for Cityscapes. You could find the definition on the configuration file if you have read the code carefully.
