### ISSUE TITLE
Asking for the matmul_norm variable why it's set as false

### ISSUE THREAD

**Issue by lawrence-cj** [wanghao9610/TMANet#20]
Hi Prof., I noticed that in your memory module, you set the 'matmul_norm' parameter as false, which in my view is opposite to the argument in the paper  《Attention is All You Need》. May I ask for the reason and whether the result will be the same if I set this variable to 'true' or not?

Have a NICE DAY!

**Comment by wanghao9610** [comment]
Hi, sorry to give a response too late. “matmul_norm” is a scale factor, it is not important to my experiments, I had tried to set "matmul_norm" to True, it didn't improve the performance. Considering the computation cost, I have set "matmul_norm" to False by default.

**Comment by lawrence-cj** [comment]
OK, copy that! Thank you so much!
