### ISSUE TITLE
关于GPU最低配置要求。

### ISSUE THREAD

**Issue by xiaweiguang** [wanghao9610/TMANet#22]
作者您好：
请问一下，笔记本电脑上的RTX3060,16G显存能跑的了1个batch吗?

**Comment by xiaweiguang** [comment]
说错了，是6GB显存

**Comment by wanghao9610** [comment]
You can try to train it with yourself, may occur an "out of memory" error. It is not recommended to train a deep network on a laptop.

**Comment by wanghao9610** [comment]
You can try to train it with yourself, may occur an "out of memory" error. It is not recommended to train a deep network on a laptop.

**Comment by xiaweiguang** [comment]
thank you
