### ISSUE TITLE
How about fist frame in a video

### ISSUE THREAD

**Issue by dreamer121121** [wanghao9610/TMANet#23]
how to predict the first frame in a video ?

**Comment by wanghao9610** [comment]
It is not an issue on Cityscapes and CamVid datasets because they don't exist a label on the first few frames. If you want to infer the first frame, you can copy the first frame multi times (sequence length, i.e. 2 or 4) for simplicity.

**Comment by dreamer121121** [comment]
Thanks a lot, i have another question about the infer speed, i test the infer speed in 1080Ti , it is about 1fps, It's that True? and why the speed is so slow?

**Comment by wanghao9610** [comment]
I have tested an image with shapes (769, 769) on cityscapes in TITAN XP, averaged 100 results, time per image is about 400~500 ms/image, fps should be about 2. It is that TMANet is a temporal-spatial attention method of which complexity is O(TN^2), the inference speed is slow as a result. We will try to improve the inference speed in our future work.
