### ISSUE TITLE
loading model camvid

### ISSUE THREAD

**Issue by LeilaMaria** [wanghao9610/TMANet#25]
Hi,

If I want to load the trained model for camvid, do I have to choose latest.pth zipped file as the checkpoint file or the data.pkl inside this file as the checkpoint??

in eval.sh, CHECKPOINT="${WORK_DIR}/latest.pth" while latest.pth is a zippped file, so I leave it like that or I unzip the file and I put CHECKPOINT="${WORK_DIR}/data.pkl", where data.pkl is inside latest.pth??

If leave latest.pth in eval.sh, I am getting this error: RuntimeError: [enforce fail at inline_container.cc:197] . file not found: archive/tensors/94018778419408

Thank you for considering my question

**Comment by abetancordelrosario** [comment]
You should leave latest.pth in the checkpoint folder. Maybe the file is corrupted, download it again.

**Comment by LeilaMaria** [comment]
Thank you . I found that the problem was using pytorch 1.4.0 instead of pytorch 1.6.0. I upgraded pytorch and the problem was resolved.

**Comment by wanghao9610** [comment]
@LeilaMaria Sorry to respond so late. It is recommended that first downloading the pre-rained model from [camvid_weight](https://drive.google.com/drive/folders/1wiKyMZItme9cb1Kfidtm4ziDT7TdrQ22) (latest.pth), then put it on this path: "./work_dirs/tmanet_r50-d8_769x769_80k_cityscapes_video/latest.pth", finally run "sh eval.sh configs/video/cityscapes/tmanet_r50-d8_769x769_80k_cityscapes_video.py" to evaluation. Hope it is helpful for you.

**Comment by LeilaMaria** [comment]
@wanghao9610 Thank you for you reply. Yes, it works. The problem was that I was using pytorch 1.4.0, so it wasn't able to load the model.
Now, it is fine :) 
Thank you :)
