### ISSUE TITLE
bad result on custom dataset

### ISSUE THREAD

**Issue by NekonoKoe** [wanghao9610/TMANet#27]
Hi, 

Thank you for your work but i have a problem. I tried to train TMANet on my custom dataset, but it produced very bad result. Other  image semantic segmentation model like OCRNet achieved far more better result on this same custom dataset than TMANet did. Is this situation normal for TMANet? and is there any way i can fix this problem? Thank you very much.

**Comment by wanghao9610** [comment]
TMANet is a video semantic segmentation, without the previous frame raltion, the performance is unexpected. And TMANet is trained on Cityscapes and Camvid datasets, the num_classes is only 19 at most, it's cross dataset performance is limited. It is not recommended that run inference on your custom dataset without model training. May be you could train TMANet on your custuom dataset, the segmentation performance will be better.

**Comment by NekonoKoe** [comment]
> 

Thank you for your reply, i did trained TMANet on my custom dataset (a video dataset built just like camvid dataset in TMANet)  and ran inference with this newly trained TMANet model, but the result is still bad. I dont know why many other models could achieve better result on the same custom dataset while TMANet cant.

**Comment by NekonoKoe** [comment]
> TMANet is a video semantic segmentation, without the previous frame raltion, the performance is unexpected. And TMANet is trained on Cityscapes and Camvid datasets, the num_classes is only 19 at most, it's cross dataset performance is limited. It is not recommended that run inference on your custom dataset without model training. May be you could train TMANet on your custuom dataset, the segmentation performance will be better.

Thank you for your reply, i did trained TMANet on my custom dataset (a video dataset built just like camvid dataset in TMANet) and ran inference with this newly trained TMANet model, but the result is still bad. I dont know why many other models could achieve better result on the same custom dataset while TMANet cant.

**Comment by wanghao9610** [comment]
I think that the reson may be the gap between datasets, the SOTA image semantic segmentation models almost trained on larger dataset with more classes (ADE20k is 150 classes vs Cityscapes is 19 classes, Camvid is 12 num_classes), TMANet's generalizaiton ability of cross datasets is limited. 
TMANet is not a gerneral semantic segmentation method, the generalizaiton ability of cross datasets is not considered.
