### ISSUE TITLE
Did you defined a new class named **CityscapesVideoDataset** ? 

### ISSUE THREAD

**Issue by Wave2689** [wanghao9610/TMANet#28]
Did you defined a new class named **CityscapesVideoDataset** ? When I run the `test.py`, there is a error `KeyError: 'CityscapesVideoDataset is not in the dataset registry'`. If you defined a new class, could you  share it please?

**Comment by Wave2689** [comment]
Sorry, I know it

**Comment by wanghao9610** [comment]
@Wave2689 Hi, You can donwload the Cityscapes sequence part from [here](https://www.cityscapes-dataset.com/downloads/).
