### ISSUE TITLE
请问能分享一下camvid的原始视频数据吗

### ISSUE THREAD

**Issue by dd1ge** [wanghao9610/TMANet#3]
您好，camvid的视频数据所在的FTP服务器貌似连不上了，在网上也没有找到原始视频数据，请问能分享一下原始视频数据吗？谢谢！！！

**Comment by dd1ge** [comment]
如果您方便分享的话，我只需要0005VD.MXF和0006R0.MXF两个数据集，谢谢您~

**Comment by wanghao9610** [comment]
Checking here:
https://drive.google.com/drive/folders/19eAfQ7Of4LUe4C4Z-S60EcTFC8BCVTr0?usp=sharing
I will save the sharing link for one month.

**Comment by dd1ge** [comment]
Thank you very much bro!!!
