### ISSUE TITLE
About the Pre-Trained Issue with GLIP

### ISSUE THREAD

**Issue by liuyang-ict** [wanghao9610/TMANet#30]
Dear Dr. Hao Wang,

I am sorry to bother you. I have read your issue with GLIP, about the implementation of pre-training. I also find this issue. When I pre-trained GLIP-T on objectv1 with 1e-5 language_backbone and 1e-4 the others, only 35 mAP was evaluated on the zero-shot COCO benchmark. 

So, I would like to know if you have solved the issue. I will be so grateful if you can share or discuss this with me. Thanks for attending this email and look forward to your reply.

Best,
Yang

**Comment by wanghao9610** [comment]
Hi, liuyang. Sorry to give a response too late, hope you have solved your issue. I pretrained the glip_Swin_T_O365 then evaluate it on zero-shot coco2017, the mAP is 43.95, while the mAP of official model weight is 44.89 (consistent with the paper reported 44.9). The gap is remained but acceptable. Hope this can help you.
