### ISSUE TITLE
Requirements for GPU Configuration in Training

### ISSUE THREAD

**Issue by XiongUp** [wanghao9610/TMANet#31]
Dear Author,
      I am planning to retrain the model and would like to know about the GPU configuration you used during your initial training. Did you use 4 graphics cards? If so, how much VRAM was required for each card?

**Comment by wanghao9610** [comment]
I have trained the model with 4 NVIDIA V100 GPUs, and the VRAM maybe 28G/32G (If my memory is not wrong😂).
