### ISSUE TITLE
Camvid dataset problem

### ISSUE THREAD

**Issue by purse1996** [wanghao9610/TMANet#4]
Can you explain how to split 'train', 'val', 'test' for video segmentation in camvid dataset. 
Thank you!
The code  is in Line 310 of camvid_video_process.py:
'''
camvid_path = "/data/datasets/video_ss/camvid/raw"
splits = ['train', 'val', 'test']
for split in splits:
    f_name = osp.join(camvid_path, f'{split}.txt')
    with open(f_name, 'w')as f:
        f_list = os.listdir(osp.join(camvid_path, split))
        for i in f_list:
            f.write(f'{i[:-4]}\n')
''''

**Comment by wanghao9610** [comment]
Check here:
https://docs.blue-oil.org/tutorial/image_seg.html

**Comment by abcdvzz** [comment]
> Check here:
> https://docs.blue-oil.org/tutorial/image_seg.html

The wget download link in this link is broken. Could you please give us another way to get the txts?
