### ISSUE TITLE
why you remove `image_sequence directory` ?

### ISSUE THREAD

**Issue by J911** [wanghao9610/TMANet#9]
`tools/convert_datasets/camvid_video_process.py` line 294

```python
    if osp.exists(save_path):
        #shutil.rmtree(save_path) <-- [??]
        pass
```

**Comment by wanghao9610** [comment]
Checking whether the image_sequence dir already esxists before generating image seqences, it is not neccessary, you can comment this line by mannually checking.

**Comment by wanghao9610** [comment]
To ensure the directory is empty, you can comment this line and manual checking.

**Comment by J911** [comment]
However, each time the directory is erased, the converted data is deleted continuously, leaving only `01TP_extract`.
```
['0005VD.MXF', '0006R0.MXF', '0016E5.MXF', '01TP_extract.avi']

1. convert 0005VD.MXF
2. del output
3. convert 0006R0.MXF
4. del output
5. ...
6. convert 01TP_extract

```

**Comment by J911** [comment]
Anyway, thank you very much for the code release.🙇‍♂️🙇‍♂️

**Comment by wanghao9610** [comment]
Hope this code base is helpful for you, please consider give me a star.
